/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gui;

/**
 *
 * @author Bart
 */
public class AddressChangeWindow extends javax.swing.JFrame {

    /**
     * Creates new form AddressChangeWindow
     */
    public AddressChangeWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Naam:");

        jLabel2.setText("Straat:");

        jLabel3.setText("Postcode:");

        jLabel4.setText("Land:");

        jLabel5.setText("Telefoon:");

        jLabel6.setText("Woonplaats:");

        phoneTextArea.setColumns(20);
        phoneTextArea.setRows(5);
        phoneTextArea.setPreferredSize(new java.awt.Dimension(164, 100));
        jScrollPane1.setViewportView(phoneTextArea);

        jScrollPane4.setViewportView(cityTextArea);

        jScrollPane5.setViewportView(streetTextArea);

        jScrollPane2.setViewportView(postcodeTextArea);

        jScrollPane3.setViewportView(countryTextArea);

        commentTextArea.setColumns(20);
        commentTextArea.setRows(5);
        commentTextArea.setPreferredSize(new java.awt.Dimension(164, 100));
        jScrollPane6.setViewportView(commentTextArea);

        jLabel7.setText("Opmerking:");

        allNamesTextArea.setColumns(20);
        allNamesTextArea.setRows(5);
        allNamesTextArea.setPreferredSize(new java.awt.Dimension(164, 100));
        jScrollPane7.setViewportView(allNamesTextArea);

        jLabel8.setText("Alle namen:");

        okButton.setText("OK");

        jScrollPane8.setViewportView(firstNameTextArea);

        jScrollPane9.setViewportView(middleNameTextArea);

        jScrollPane10.setViewportView(lastNameTextArea);

        cancelButton.setText("Annuleer");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(cancelButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(okButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel2)
                            .addComponent(jLabel8)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                                    .addComponent(jScrollPane4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane3)
                                    .addComponent(jScrollPane2)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                            .addComponent(jScrollPane6)
                            .addComponent(jScrollPane7)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane10)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okButton)
                    .addComponent(cancelButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

   

    // Variables declaration - do not modify                     
    public final javax.swing.JTextArea allNamesTextArea = new javax.swing.JTextArea();
    public final javax.swing.JButton cancelButton = new javax.swing.JButton();
    public final javax.swing.JTextPane cityTextArea = new javax.swing.JTextPane();
    public final javax.swing.JTextArea commentTextArea = new javax.swing.JTextArea();
    public final javax.swing.JTextPane countryTextArea = new javax.swing.JTextPane();
    public final javax.swing.JTextPane firstNameTextArea = new javax.swing.JTextPane();
    public final javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
    public final javax.swing.JLabel jLabel2 = new javax.swing.JLabel();
    public final javax.swing.JLabel jLabel3 = new javax.swing.JLabel();
    public final javax.swing.JLabel jLabel4 = new javax.swing.JLabel();
    public final javax.swing.JLabel jLabel5 = new javax.swing.JLabel();
    public final javax.swing.JLabel jLabel6 = new javax.swing.JLabel();
    public final javax.swing.JLabel jLabel7 = new javax.swing.JLabel();
    public final javax.swing.JLabel jLabel8 = new javax.swing.JLabel();
    public final javax.swing.JScrollPane jScrollPane1 = new javax.swing.JScrollPane();
    public final javax.swing.JScrollPane jScrollPane10 = new javax.swing.JScrollPane();
    public final javax.swing.JScrollPane jScrollPane2 = new javax.swing.JScrollPane();
    public final javax.swing.JScrollPane jScrollPane3 = new javax.swing.JScrollPane();
    public final javax.swing.JScrollPane jScrollPane4 = new javax.swing.JScrollPane();
    public final javax.swing.JScrollPane jScrollPane5 = new javax.swing.JScrollPane();
    public final javax.swing.JScrollPane jScrollPane6 = new javax.swing.JScrollPane();
    public final javax.swing.JScrollPane jScrollPane7 = new javax.swing.JScrollPane();
    public final javax.swing.JScrollPane jScrollPane8 = new javax.swing.JScrollPane();
    public final javax.swing.JScrollPane jScrollPane9 = new javax.swing.JScrollPane();
    public final javax.swing.JTextPane lastNameTextArea = new javax.swing.JTextPane();
    public final javax.swing.JTextPane middleNameTextArea = new javax.swing.JTextPane();
    public final javax.swing.JButton okButton = new javax.swing.JButton();
    public final javax.swing.JTextArea phoneTextArea = new javax.swing.JTextArea();
    public final javax.swing.JTextPane postcodeTextArea = new javax.swing.JTextPane();
    public final javax.swing.JTextPane streetTextArea = new javax.swing.JTextPane();
    // End of variables declaration                   
}
